### ISSUE TITLE
Add User Page Skeleton 

### ISSUE THREAD

**Issue by rspoojara** [rspoojara/SMART-FACE-DETECTION-SYSTEM#1]
We have submitted the **Add User Page Form** Fields in the repository. Please refer it and create the Add user page Skeleton. Select the Appropriate Technology for the UI designing and mention it.

**Comment by Aelisha-12** [comment]
we completed the skeleton . In which we design three pages Add user , Login page , Home page . In add user we add some field . In Login page three button .
