### ISSUE TITLE
Implementing Validation for Sign-in page

### ISSUE THREAD

**Issue by Kushang05** [rspoojara/SMART-FACE-DETECTION-SYSTEM#3]
There are two fields in this page named as User Name and Password.
For these you need to write every possible validation requirement facilities that can be implemented.
###
The password field should contain at least one lower case , upper case , a number and special character.

**Comment by Pratiksha-Shitole** [comment]
-> Implemented The validation Part for sign-in Page.
-> Added the validation Like Username Field not should  Not be empty and password should contain one lower case ,Upper Case ,a Number and Some special Character.
